### ISSUE TITLE
Issue when running the efficiency branch

### ISSUE THREAD

**Issue by benryandev** [tuanle618/neural-net-random-art#2] opened 2022-01-20 00:04 UTC
I received the below error when running the efficiency branch. Also can it output the vectored image as SVG?
python random_art.py

Using vectorized computation.
Generating image number 1...
Traceback (most recent call last):
  File "/Users/benryan/Neural Art Efficiency/random_art.py", line 602, in <module>
    main()
  File "/Users/benryan/Neural Art Efficiency/random_art.py", line 589, in main
    my_net = TorchNeuralNet(layers_dims=[n_size]*n_depth, activation_fnc=activation,
  File "/Users/benryan/Neural Art Efficiency/random_art.py", line 50, in __init__
    self.output_layer = nn.Linear(in_features=layers_dims[-1], out_features=out_nodes)
UnboundLocalError: local variable 'out_nodes' referenced before assignment

**Comment by tuanle618** [comment] 2022-01-29 17:29
Hi @benryandev, I'll refactor the code the upcoming days and will update you once its done!
To answer your question regarding the SVG dataformat. I think this should be feasible with matplotlib. 
As mentioned, I'll write you once I finished the refactoring.

Cheers,
Tuan

**Comment by benryandev** [comment] 2022-01-29 20:09
Thank you very much. I truly appreciate it

**Comment by tuanle618** [comment] 2022-01-30 18:04
Hey @benryandev, I've updated the repo and merged the changes into the main branch. If you run the main python programe, you can add a flag `-format svg`.
Could you give it a try?

Best,
Tuan

**Comment by benryandev** [comment] 2022-02-08 03:35
Since the repo merge, it seems everytime colormode "rgb" runs, it uses the exact same colors

**Comment by tuanle618** [comment] 2022-03-07 07:58
Hey @benryandev , I cannot reproduce the same-color behaviour. When I run the main commands, I get different coloured-images. Gonna update the main branch later with the default args.

**Closed as completed** 2022-03-07 08:36 UTC
